name: Build CrossSine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon
      
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: CrossSine-Build
          path: build/libs/*.jar
